# -*- coding: utf-8 -*-
"""Копия блокнота "Untitled10.ipynb"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vMX1sa4XoZ18fkEh_ZOQdj1PJHYu9lZH
"""

def dfs(graph, start, visited=None):
    if visited is None:
        visited = set()
    visited.add(start)

    print(start)

    for next in graph[start] - visited:
        dfs(graph, next, visited)
    return visited


graph = {'0': set(['1', '2']),
         '1': set(['0', '3', '4']),
         '2': set(['0']),
         '3': set(['1']),
         '4': set(['2', '3'])}

dfs(graph, '0')